# RosebankCollageMagazine
THIS IS A MAGAZINE FOR BOTH STUDENTS AND THE STUFF OF THE FUCULTY 
ROSEBANK COLLAGE/ OR ANYONE RELATED TO ANYKIND OF MOVEMENT THE 
COLLAGE IS HAVING (e.g. PARENTS/SCHOOLFEES PAYER). THIS IS ABOUT THE 
EXPRESSIONS AND EXPERIENCES ABOUT THE SCHOOL AND THE MOTION THE 
STUDENTS SHARE AMONST THEMSELVES.  
THE PURPOSE OF THIS MAGAZINE IS TO ESCALATE AND LEAK VALUABLE 
INFORMATION SPECIFICALLY FOR STUDENTS TO GET THEIR HEADS TO THINKING 
THE RIGHT INFORMATION, INFORMATION THAT WILL HELP THEM IN THE FUTURE; 
ALSO, A PLATFORM FOR STUDENTS TO EXPRESS THEIR CREATIVITY, AND 
ACADEEMIC INSIGHTS; TO TEACH THEM AND REMIND THEM TO ALWAYS FOLLOW 
THE RIGHT CHOICES. MOSTLY TO REMIND THE STUDENTS HOW IMPORTANT THEY 
ARE TO ONE ANOTHER, ALSO TO BRING OR SHARE EMOTION TO REMIND 
THEMSELVES TO NOT BE AFRAID OF THE FUTURE AS THEY ARE THE LIGHT THEY 
WANT TO SEE. TO REMIND THEM THEY ARE ALL THEY NEED TO SHAPE THE LIGHT 
OF THE FUTURE.  
THE MAGAZINE WILL BE PRODUCES WEEKLY AND WILL BE BOTH INFORMATIVE 
AND ENTERTAINING FOR STUDENTS, STAFF, AND THE FACULTY. IT WILL SUPPORT 
COMMMUNITY ENGAGEMENT AND SHOWCASE THE DIVERSE TALENTS OF THE 
STUDENT BORDY
